print("Hello Genius")
print("                 /|")
print("                / |")
print("               /  |")
print("              /   |")
print("             /    |")
print("            /     |")
print("           /      |")
print("          /       |")
print("         /        |")
print("        /         |")
print("       /          |")
print("      /___________|")
print("     /\          /")
print("    /  \        /")
print("   /    \      /")
print("  /      \    /")
print(" /        \  /")
print("/          \/")
print("WORKING WITH STRINGS")
character_name = "Genius"
character_age = "30"
print("There was once a boy named " + character_name + ",")
print("he was " + character_age + " years old.")
print("He loved being Genius,")
print("but he hated being " + character_age + " years old.")
print('Genius The Great')
print('Genius \nThe Great')
print('Genius /nThe Great')
print('Genius \"The Great !!!!"')
phrase = "Genius Dexter"
print(phrase + " is good")
print(phrase.upper())
print(phrase.lower().islower)
print(phrase.lower().isupper())
print(len(phrase))
print(phrase[5])
print(phrase.count("g"))
print(phrase.index("D"))
print(phrase.replace("Genius","Caius"))

print("WORKING WITH NUMBERS")
print(7.788746)
print(3 * 5 + 4)
print((3 * 4) + 5)
print("THE SIGN '%' READS MODULUS IN PYTHON PROGRAMMING.")
print("For example,")
print("'20 % 5', reads 'Twenty Modulo Five,")
print("and so gives '0' as in normal Mathematics")
print(20 % 5)
print(13 % 8)
print(43 % 9)
my_num = 7
print(my_num)
print(str(my_num) + " is my Lucky Number")
my_num = -10
print(abs(my_num))
print("pow(3, 2)")
pow(3, 2)
print("THE EXPRESSION ABOVE READS, 'THREE TO POWER TWO'")
print(pow(3, 2))
print(max(4, 6))
print(min(4, 6))
print(round(6.456))
print(round(6.56,))
print(round(3.14))
from math import *
print(floor(6.5))
print(floor(6.3))
print(floor(3.7))
print(ceil(7.4))
print(ceil(7.7))
print(ceil(2.3))

print(float(56))
roommates = ["Ifechukwu", "Michael", "Paul", "Christian"]
print(roommates)
print(roommates[0])
print(roommates[-1])
print(roommates[3])
print("I" + ", " + roommates[0] + ", " + roommates[1] + " and " + roommates[3] + " are always in the Room.")

friends = roommates.copy
print(friends)


n_o_a = (1, 3, 2, 4)
print(n_o_a)

roommates.append("Emmanuel")
print(roommates)
roommates.reverse()
print(roommates)
roommates.sort()
print(roommates)
roommates.insert(3, "Okechukwu")
print(roommates)
roommates.extend(n_o_a)
print(roommates)

